#!/bin/bash
# Code generated by protoc-gen-liquibase. DO NOT EDIT.

# Command Arguments
AUTHOR=${1}
CHANGELOGFILE=${2}
COMPARECONTROL=${3}
CONTEXT=${4}
DATAOUTPUTDIRECTORY=${5}
DATABASE=${6}
DEFAULTCATALOGNAME=${7}
DEFAULTSCHEMANAME=${8}
DIFFTYPES=${9}
DRIVER=${10}
DRIVERPROPERTIESFILE=${11}
EXCLUDEOBJECTS=${12}
FORMAT=${13}
INCLUDECATALOG=${14}
INCLUDEOBJECTS=${15}
INCLUDESCHEMA=${16}
INCLUDETABLESPACE=${17}
OBJECTCHANGEFILTER=${18}
OUTPUTSCHEMAS=${19}
OVERWRITEOUTPUTFILE=${20}
PASSWORD=${21}
REFERENCEDATABASE=${22}
REFERENCEDEFAULTCATALOGNAME=${23}
REFERENCEDEFAULTSCHEMANAME=${24}
REFERENCEDRIVER=${25}
REFERENCEDRIVERPROPERTIESFILE=${26}
REFERENCEPASSWORD=${27}
REFERENCESCHEMAS=${28}
REFERENCESNAPSHOTCONTROL=${29}
REFERENCEURL=${30}
REFERENCEUSERNAME=${31}
SCHEMAS=${32}
SKIPDATABASESTEP=${33}
SNAPSHOTLISTENER=${34}
SNAPSHOTTYPES=${35}
TARGETSNAPSHOTCONTROL=${36}
URL=${37}
USERNAME=${38}
# Global Options
ALWAYSDROPINSTEADOFREPLACE=${39}
ALWAYSOVERRIDESTOREDLOGICSCHEMA=${40}
AUTOREORG=${41}
CHANGELOGLOCKPOLLRATE=${42}
CHANGELOGLOCKWAITTIMEINMINUTES=${43}
CHANGELOGPARSEMODE=${44}
CLASSPATH=${45}
CONVERTDATATYPES=${46}
DATABASECHANGELOGLOCKTABLENAME=${47}
DATABASECHANGELOGTABLENAME=${48}
DATABASECLASS=${49}
DDLLOCKTIMEOUT=${50}
DEFAULTSFILE=${51}
DIFFCOLUMNORDER=${52}
DUPLICATEFILEMODE=${53}
ERRORONCIRCULARINCLUDEALL=${54}
FILEENCODING=${55}
FILTERLOGMESSAGES=${56}
GENERATECHANGESETCREATEDVALUES=${57}
GENERATEDCHANGESETIDSCONTAINSDESCRIPTION=${58}
HEADLESS=${59}
HUBAPIKEY=${60}
HUBLOGLEVEL=${61}
HUBMODE=${62}
HUBURL=${63}
INCLUDECATALOGINSPECIFICATION=${64}
INCLUDESYSTEMCLASSPATH=${65}
LICENSEKEY=${66}
LIQUIBASECATALOGNAME=${67}
LIQUIBASESCHEMANAME=${68}
LIQUIBASETABLESPACENAME=${69}
LOGCHANNELS=${70}
LOGFILE=${71}
LOGFORMAT=${72}
LOGLEVEL=${73}
MISSINGPROPERTYMODE=${74}
MONITORPERFORMANCE=${75}
NATIVEEXECUTOR=${76}
ONMISSINGINCLUDE=${77}
OUTPUTFILE=${78}
OUTPUTFILEENCODING=${79}
OUTPUTLINESEPARATOR=${80}
PRESERVESCHEMACASE=${81}
PROLICENSEKEY=${82}
PROMARKUNUSEDNOTDROP=${83}
PROSQLINLINE=${84}
PROSYNONYMSDROPPUBLIC=${85}
PROMPTFORNONLOCALDATABASE=${86}
PROPERTYPROVIDERCLASS=${87}
SEARCHPATH=${88}
SECUREPARSING=${89}
SHOULDRUN=${90}
SHOULDSNAPSHOTDATA=${91}
SHOWBANNER=${92}
SQLLOGLEVEL=${93}
STRICT=${94}
SUPPORTPROPERTYESCAPING=${95}
USEPROCEDURESCHEMA=${96}
VALIDATEXMLCHANGELOGFILES=${97}

if [[ -z "$URL" ]]; then
	echo "url is required"
	exit 1
fi

PARAMS=()

if [[ -n "$AUTHOR" ]]; then
	PARAMS+=("--author=$AUTHOR")
fi
if [[ -n "$CHANGELOGFILE" ]]; then
	PARAMS+=("--changelog-file=$CHANGELOGFILE")
fi
if [[ -n "$COMPARECONTROL" ]]; then
	PARAMS+=("--compare-control=$COMPARECONTROL")
fi
if [[ -n "$CONTEXT" ]]; then
	PARAMS+=("--context=$CONTEXT")
fi
if [[ -n "$DATAOUTPUTDIRECTORY" ]]; then
	PARAMS+=("--data-output-directory=$DATAOUTPUTDIRECTORY")
fi
if [[ -n "$DATABASE" ]]; then
	PARAMS+=("--database=$DATABASE")
fi
if [[ -n "$DEFAULTCATALOGNAME" ]]; then
	PARAMS+=("--default-catalog-name=$DEFAULTCATALOGNAME")
fi
if [[ -n "$DEFAULTSCHEMANAME" ]]; then
	PARAMS+=("--default-schema-name=$DEFAULTSCHEMANAME")
fi
if [[ -n "$DIFFTYPES" ]]; then
	PARAMS+=("--diff-types=$DIFFTYPES")
fi
if [[ -n "$DRIVER" ]]; then
	PARAMS+=("--driver=$DRIVER")
fi
if [[ -n "$DRIVERPROPERTIESFILE" ]]; then
	PARAMS+=("--driver-properties-file=$DRIVERPROPERTIESFILE")
fi
if [[ -n "$EXCLUDEOBJECTS" ]]; then
	PARAMS+=("--exclude-objects=$EXCLUDEOBJECTS")
fi
if [[ -n "$FORMAT" ]]; then
	PARAMS+=("--format=$FORMAT")
fi
if [[ -n "$INCLUDECATALOG" ]]; then
	PARAMS+=("--include-catalog=$INCLUDECATALOG")
fi
if [[ -n "$INCLUDEOBJECTS" ]]; then
	PARAMS+=("--include-objects=$INCLUDEOBJECTS")
fi
if [[ -n "$INCLUDESCHEMA" ]]; then
	PARAMS+=("--include-schema=$INCLUDESCHEMA")
fi
if [[ -n "$INCLUDETABLESPACE" ]]; then
	PARAMS+=("--include-tablespace=$INCLUDETABLESPACE")
fi
if [[ -n "$OBJECTCHANGEFILTER" ]]; then
	PARAMS+=("--object-change-filter=$OBJECTCHANGEFILTER")
fi
if [[ -n "$OUTPUTSCHEMAS" ]]; then
	PARAMS+=("--output-schemas=$OUTPUTSCHEMAS")
fi
if [[ -n "$OVERWRITEOUTPUTFILE" ]]; then
	PARAMS+=("--overwrite-output-file=$OVERWRITEOUTPUTFILE")
fi
if [[ -n "$PASSWORD" ]]; then
	PARAMS+=("--password=$PASSWORD")
fi
if [[ -n "$REFERENCEDATABASE" ]]; then
	PARAMS+=("--reference-database=$REFERENCEDATABASE")
fi
if [[ -n "$REFERENCEDEFAULTCATALOGNAME" ]]; then
	PARAMS+=("--reference-default-catalog-name=$REFERENCEDEFAULTCATALOGNAME")
fi
if [[ -n "$REFERENCEDEFAULTSCHEMANAME" ]]; then
	PARAMS+=("--reference-default-schema-name=$REFERENCEDEFAULTSCHEMANAME")
fi
if [[ -n "$REFERENCEDRIVER" ]]; then
	PARAMS+=("--reference-driver=$REFERENCEDRIVER")
fi
if [[ -n "$REFERENCEDRIVERPROPERTIESFILE" ]]; then
	PARAMS+=("--reference-driver-properties-file=$REFERENCEDRIVERPROPERTIESFILE")
fi
if [[ -n "$REFERENCEPASSWORD" ]]; then
	PARAMS+=("--reference-password=$REFERENCEPASSWORD")
fi
if [[ -n "$REFERENCESCHEMAS" ]]; then
	PARAMS+=("--reference-schemas=$REFERENCESCHEMAS")
fi
if [[ -n "$REFERENCESNAPSHOTCONTROL" ]]; then
	PARAMS+=("--reference-snapshot-control=$REFERENCESNAPSHOTCONTROL")
fi
if [[ -n "$REFERENCEURL" ]]; then
	PARAMS+=("--reference-url=$REFERENCEURL")
fi
if [[ -n "$REFERENCEUSERNAME" ]]; then
	PARAMS+=("--reference-username=$REFERENCEUSERNAME")
fi
if [[ -n "$SCHEMAS" ]]; then
	PARAMS+=("--schemas=$SCHEMAS")
fi
if [[ -n "$SKIPDATABASESTEP" ]]; then
	PARAMS+=("--skip-database-step=$SKIPDATABASESTEP")
fi
if [[ -n "$SNAPSHOTLISTENER" ]]; then
	PARAMS+=("--snapshot-listener=$SNAPSHOTLISTENER")
fi
if [[ -n "$SNAPSHOTTYPES" ]]; then
	PARAMS+=("--snapshot-types=$SNAPSHOTTYPES")
fi
if [[ -n "$TARGETSNAPSHOTCONTROL" ]]; then
	PARAMS+=("--target-snapshot-control=$TARGETSNAPSHOTCONTROL")
fi
if [[ -n "$URL" ]]; then
	PARAMS+=("--url=$URL")
fi
if [[ -n "$USERNAME" ]]; then
	PARAMS+=("--username=$USERNAME")
fi

GLOBALS=()

if [[ -n "$ALWAYSDROPINSTEADOFREPLACE" ]]; then
	GLOBALS+=("--always-drop-instead-of-replace=$ALWAYSDROPINSTEADOFREPLACE")
fi
if [[ -n "$ALWAYSOVERRIDESTOREDLOGICSCHEMA" ]]; then
	GLOBALS+=("--always-override-stored-logic-schema=$ALWAYSOVERRIDESTOREDLOGICSCHEMA")
fi
if [[ -n "$AUTOREORG" ]]; then
	GLOBALS+=("--auto-reorg=$AUTOREORG")
fi
if [[ -n "$CHANGELOGLOCKPOLLRATE" ]]; then
	GLOBALS+=("--changelog-lock-poll-rate=$CHANGELOGLOCKPOLLRATE")
fi
if [[ -n "$CHANGELOGLOCKWAITTIMEINMINUTES" ]]; then
	GLOBALS+=("--changelog-lock-wait-time-in-minutes=$CHANGELOGLOCKWAITTIMEINMINUTES")
fi
if [[ -n "$CHANGELOGPARSEMODE" ]]; then
	GLOBALS+=("--changelog-parse-mode=$CHANGELOGPARSEMODE")
fi
if [[ -n "$CLASSPATH" ]]; then
	GLOBALS+=("--classpath=$CLASSPATH")
fi
if [[ -n "$CONVERTDATATYPES" ]]; then
	GLOBALS+=("--convert-data-types=$CONVERTDATATYPES")
fi
if [[ -n "$DATABASECHANGELOGLOCKTABLENAME" ]]; then
	GLOBALS+=("--database-changelog-lock-table-name=$DATABASECHANGELOGLOCKTABLENAME")
fi
if [[ -n "$DATABASECHANGELOGTABLENAME" ]]; then
	GLOBALS+=("--database-changelog-table-name=$DATABASECHANGELOGTABLENAME")
fi
if [[ -n "$DATABASECLASS" ]]; then
	GLOBALS+=("--database-class=$DATABASECLASS")
fi
if [[ -n "$DDLLOCKTIMEOUT" ]]; then
	GLOBALS+=("--ddl-lock-timeout=$DDLLOCKTIMEOUT")
fi
if [[ -n "$DEFAULTSFILE" ]]; then
	GLOBALS+=("--defaults-file=$DEFAULTSFILE")
fi
if [[ -n "$DIFFCOLUMNORDER" ]]; then
	GLOBALS+=("--diff-column-order=$DIFFCOLUMNORDER")
fi
if [[ -n "$DUPLICATEFILEMODE" ]]; then
	GLOBALS+=("--duplicate-file-mode=$DUPLICATEFILEMODE")
fi
if [[ -n "$ERRORONCIRCULARINCLUDEALL" ]]; then
	GLOBALS+=("--error-on-circular-include-all=$ERRORONCIRCULARINCLUDEALL")
fi
if [[ -n "$FILEENCODING" ]]; then
	GLOBALS+=("--file-encoding=$FILEENCODING")
fi
if [[ -n "$FILTERLOGMESSAGES" ]]; then
	GLOBALS+=("--filter-log-messages=$FILTERLOGMESSAGES")
fi
if [[ -n "$GENERATECHANGESETCREATEDVALUES" ]]; then
	GLOBALS+=("--generate-changeset-created-values=$GENERATECHANGESETCREATEDVALUES")
fi
if [[ -n "$GENERATEDCHANGESETIDSCONTAINSDESCRIPTION" ]]; then
	GLOBALS+=("--generated-changeset-ids-contains-description=$GENERATEDCHANGESETIDSCONTAINSDESCRIPTION")
fi
if [[ -n "$HEADLESS" ]]; then
	GLOBALS+=("--headless=$HEADLESS")
fi
if [[ -n "$HUBAPIKEY" ]]; then
	GLOBALS+=("--hub-api-key=$HUBAPIKEY")
fi
if [[ -n "$HUBLOGLEVEL" ]]; then
	GLOBALS+=("--hub-log-level=$HUBLOGLEVEL")
fi
if [[ -n "$HUBMODE" ]]; then
	GLOBALS+=("--hub-mode=$HUBMODE")
fi
if [[ -n "$HUBURL" ]]; then
	GLOBALS+=("--hub-url=$HUBURL")
fi
if [[ -n "$INCLUDECATALOGINSPECIFICATION" ]]; then
	GLOBALS+=("--include-catalog-in-specification=$INCLUDECATALOGINSPECIFICATION")
fi
if [[ -n "$INCLUDESYSTEMCLASSPATH" ]]; then
	GLOBALS+=("--include-system-classpath=$INCLUDESYSTEMCLASSPATH")
fi
if [[ -n "$LICENSEKEY" ]]; then
	GLOBALS+=("--license-key=$LICENSEKEY")
fi
if [[ -n "$LIQUIBASECATALOGNAME" ]]; then
	GLOBALS+=("--liquibase-catalog-name=$LIQUIBASECATALOGNAME")
fi
if [[ -n "$LIQUIBASESCHEMANAME" ]]; then
	GLOBALS+=("--liquibase-schema-name=$LIQUIBASESCHEMANAME")
fi
if [[ -n "$LIQUIBASETABLESPACENAME" ]]; then
	GLOBALS+=("--liquibase-tablespace-name=$LIQUIBASETABLESPACENAME")
fi
if [[ -n "$LOGCHANNELS" ]]; then
	GLOBALS+=("--log-channels=$LOGCHANNELS")
fi
if [[ -n "$LOGFILE" ]]; then
	GLOBALS+=("--log-file=$LOGFILE")
fi
if [[ -n "$LOGFORMAT" ]]; then
	GLOBALS+=("--log-format=$LOGFORMAT")
fi
if [[ -n "$LOGLEVEL" ]]; then
	GLOBALS+=("--log-level=$LOGLEVEL")
fi
if [[ -n "$MISSINGPROPERTYMODE" ]]; then
	GLOBALS+=("--missing-property-mode=$MISSINGPROPERTYMODE")
fi
if [[ -n "$MONITORPERFORMANCE" ]]; then
	GLOBALS+=("--monitor-performance=$MONITORPERFORMANCE")
fi
if [[ -n "$NATIVEEXECUTOR" ]]; then
	GLOBALS+=("--native-executor=$NATIVEEXECUTOR")
fi
if [[ -n "$ONMISSINGINCLUDE" ]]; then
	GLOBALS+=("--on-missing-include=$ONMISSINGINCLUDE")
fi
if [[ -n "$OUTPUTFILE" ]]; then
	GLOBALS+=("--output-file=$OUTPUTFILE")
fi
if [[ -n "$OUTPUTFILEENCODING" ]]; then
	GLOBALS+=("--output-file-encoding=$OUTPUTFILEENCODING")
fi
if [[ -n "$OUTPUTLINESEPARATOR" ]]; then
	GLOBALS+=("--output-line-separator=$OUTPUTLINESEPARATOR")
fi
if [[ -n "$PRESERVESCHEMACASE" ]]; then
	GLOBALS+=("--preserve-schema-case=$PRESERVESCHEMACASE")
fi
if [[ -n "$PROLICENSEKEY" ]]; then
	GLOBALS+=("--pro-license-key=$PROLICENSEKEY")
fi
if [[ -n "$PROMARKUNUSEDNOTDROP" ]]; then
	GLOBALS+=("--pro-mark-unused-not-drop=$PROMARKUNUSEDNOTDROP")
fi
if [[ -n "$PROSQLINLINE" ]]; then
	GLOBALS+=("--pro-sql-inline=$PROSQLINLINE")
fi
if [[ -n "$PROSYNONYMSDROPPUBLIC" ]]; then
	GLOBALS+=("--pro-synonyms-drop-public=$PROSYNONYMSDROPPUBLIC")
fi
if [[ -n "$PROMPTFORNONLOCALDATABASE" ]]; then
	GLOBALS+=("--prompt-for-non-local-database=$PROMPTFORNONLOCALDATABASE")
fi
if [[ -n "$PROPERTYPROVIDERCLASS" ]]; then
	GLOBALS+=("--property-provider-class=$PROPERTYPROVIDERCLASS")
fi
if [[ -n "$SEARCHPATH" ]]; then
	GLOBALS+=("--search-path=$SEARCHPATH")
fi
if [[ -n "$SECUREPARSING" ]]; then
	GLOBALS+=("--secure-parsing=$SECUREPARSING")
fi
if [[ -n "$SHOULDRUN" ]]; then
	GLOBALS+=("--should-run=$SHOULDRUN")
fi
if [[ -n "$SHOULDSNAPSHOTDATA" ]]; then
	GLOBALS+=("--should-snapshot-data=$SHOULDSNAPSHOTDATA")
fi
if [[ -n "$SHOWBANNER" ]]; then
	GLOBALS+=("--show-banner=$SHOWBANNER")
fi
if [[ -n "$SQLLOGLEVEL" ]]; then
	GLOBALS+=("--sql-log-level=$SQLLOGLEVEL")
fi
if [[ -n "$STRICT" ]]; then
	GLOBALS+=("--strict=$STRICT")
fi
if [[ -n "$SUPPORTPROPERTYESCAPING" ]]; then
	GLOBALS+=("--support-property-escaping=$SUPPORTPROPERTYESCAPING")
fi
if [[ -n "$USEPROCEDURESCHEMA" ]]; then
	GLOBALS+=("--use-procedure-schema=$USEPROCEDURESCHEMA")
fi
if [[ -n "$VALIDATEXMLCHANGELOGFILES" ]]; then
	GLOBALS+=("--validate-xml-changelog-files=$VALIDATEXMLCHANGELOGFILES")
fi

docker-entrypoint.sh "${GLOBALS[@]}" generate-changelog "${PARAMS[@]}"
